name: Windows Build Only

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Build Tag"
        required: true

jobs:
  # 1. Собираем Go-часть (ядро)
  build-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Build Go
        run: |
          ./libs/get_source.sh
          GOOS=windows GOARCH=amd64 ./libs/build_go.sh
          ./libs/build_public_res.sh
      - name: Upload Go Artifact
        uses: actions/upload-artifact@v4
        with:
          name: go-artifacts
          path: deployment/

  # 2. Собираем интерфейс на Qt (Windows)
  build-windows:
    needs: build-go
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Download Go Artifacts
        uses: actions/download-artifact@v4
        with:
          name: go-artifacts
          path: deployment/
      - name: Install MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          toolset: 14.2
      - name: Install Qt
        shell: bash
        run: bash ./libs/download_qtsdk_win.sh
      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@v4
      - name: Build Deps
        shell: bash
        run: ./libs/build_deps_all.sh
      - name: Build NekoBox
        shell: bash
        env:
          DL_QT_VER: "6.7"
        run: |
          source libs/env_qtsdk.sh $PWD/qtsdk/Qt
          mkdir build && cd build
          cmake -GNinja -DQT_VERSION_MAJOR=6 -DCMAKE_BUILD_TYPE=Release ..
          ninja
          cd ..
          ./libs/deploy_windows64.sh
      - name: Create Final Zip
        shell: bash
        run: |
          cp -r deployment/public_res/* deployment/windows64/
          cd deployment/windows64
          7z a ../../NekoBox-Windows.zip *
      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: NekoBox-Custom-Build
          path: NekoBox-Windows.zip
